<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AutoMapper\**" />
    <Compile Remove="ViewModels\**" />
    <EmbeddedResource Remove="AutoMapper\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="AutoMapper\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LEA.WebApi.Domain\LEA.WebApi.Domain.csproj" />
  </ItemGroup>

</Project>
