name: CI/CD - Build, Version and Deploy

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI - Build and Push Image
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ler versão
        id: version
        run: |
          VERSION=$(tr -d '\r\n' < VERSION)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            171388/lea-api:${{ steps.version.outputs.version }}
            171388/lea-api:latest

  cd:
    name: CD - Deploy automático na VM
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/lea-webapi
            
            echo "🧹 Limpando imagens antigas..."
            docker image prune -af
            
            export IMAGE_TAG=${{ needs.ci.outputs.version }}
            echo "Deployando versão: $IMAGE_TAG"
            
            docker compose pull
            docker compose up -d
