name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.234.228.70
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/lea-webapi
            docker compose pull
            docker compose up -d
